---
pkg_url_base: "file://{{ ansible_env.HOME }}/powerflex_rpms"
pkg_url:
  lia: "{{ pkg_url_base }}/EMC-ScaleIO-lia-3.6-700.103.el8.x86_64.rpm"
  mdm: "{{ pkg_url_base }}/EMC-ScaleIO-mdm-3.6-700.103.el8.x86_64.rpm"
  sds: "{{ pkg_url_base }}/EMC-ScaleIO-sds-3.6-700.103.el8.x86_64.rpm"
  sdc: "{{ pkg_url_base }}/EMC-ScaleIO-sdc-3.6-700.103.el8.x86_64.rpm"
  gateway: "{{ pkg_url_base }}/EMC-ScaleIO-gateway-3.6-700.103.x86_64.rpm"
  presentation: "{{ pkg_url_base }}/EMC-ScaleIO-mgmt-server-3.6-700.101.noarch.rpm"
lia_token: ~
mdm_ip: []
gateway_admin_password: ~
mdm_password: ~
scaleio_dir: "/opt/emc/scaleio"
gateway_user_properties_file: "{{ scaleio_dir }}/gateway/webapps/ROOT/WEB-INF/classes/gatewayUser.properties"
mdm_ip_addresses: >-
  [
    "{{ hostvars[groups['mdm'][0]]['ansible_'+mgmt_iface_name].ipv4.address }}",
    "{{ hostvars[groups['mdm'][1]]['ansible_'+mgmt_iface_name].ipv4.address }}",
  {% for siface in storage_iface_names %}
    "{{ hostvars[groups['mdm'][0]]['ansible_'+siface].ipv4.address }}",
    "{{ hostvars[groups['mdm'][1]]['ansible_'+siface].ipv4.address }}",
  {% endfor %}
  ]

catalina_properties_file: "{{ scaleio_dir }}/gateway/conf/catalina.properties"
gateway_http_port: 80
gateway_ssl_port: 443

lia_conf_file: "{{ scaleio_dir }}/lia/cfg/conf.txt"
lia_port: 9099

presentation_conf_file: "/etc/mgmt-server/.config/mgmt-server"
presentation_port: 8443
...
