---
- name: genesis registry restart service
  service:
    name: "genesis_registry.service"
    state: "restarted"
    enabled: true
  become: true
  changed_when: false

- name: haproxy reload service
  service:
    name: "haproxy.service"
    state: "reloaded"
    enabled: true
  become: true
  changed_when: false

- name: kubelet restart service
  service:
    name: "kubelet.service"
    state: "restarted"
    enabled: true
  become: true
  changed_when: false
...
