---
- name: Deploy ceph-csi playbook
  any_errors_fatal: true
  ansible.builtin.import_playbook: kubespray/ceph-csi.yml
  tags: ceph-csi

- name: Deploy cri patch playbook
  any_errors_fatal: true
  ansible.builtin.import_playbook: cripatch.yml
  tags: cripatch-burrito

- name: Deploy k8s patch playbook
  any_errors_fatal: true
  ansible.builtin.import_playbook: k8spatch.yml
  tags: k8spatch-burrito
...
