---
- name: Run preflight checklist
  any_errors_fatal: true
  ansible.builtin.import_playbook: checklist.yml
  tags: checklist

- name: Deploy common service
  hosts: all
  any_errors_fatal: true
  roles:
    - {role: burrito.common, tags: ['common']}

- name: Deploy ntp service
  hosts: all
  any_errors_fatal: true
  roles:
    - {role: burrito.ntp, tags: ['ntp']}
...
