---
- name: Provision | create ceph-csi namespace
  community.kubernetes.k8s:
    name: ceph-csi
    api_version: v1
    kind: Namespace
    state: present
  become: true

- name: Provision | create ceph-csi artifacts directory
  ansible.builtin.file:
    path: "{{ artifacts_dir }}"
    state: directory

- name: Provision | copy ceph-csi static files
  ansible.builtin.copy:
    dest: "{{ artifacts_dir }}/{{ item | basename }}"
    src: "{{ item }}"
    mode: "0644"
  with_fileglob:
    - "files/*"

- name: Provision | get ceph cluster id
  ansible.builtin.command: >-
    ceph config get mon fsid
  register: result
  become: true

- name: Provision | set fact for ceph cluster id
  ansible.builtin.set_fact:
    ceph_cluster_id: "{{ result.stdout }}"

- name: Provision | get client.kube keyring
  ansible.builtin.command: >-
    ceph auth get-key client.kube
  register: result
  become: true

- name: Provision | set fact for kube keyring
  ansible.builtin.set_fact:
    ceph_user_key: "{{ result.stdout }}"

- name: Provision | templating ceph-csi template files
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ item.dest | basename }}.j2"
    mode: "0644"
  loop: "{{ template_files }}"

- name: Provision | apply ceph-csi manifests
  community.kubernetes.k8s:
    src: "{{ item }}"
    state: present
  with_fileglob:
    - "{{ artifacts_dir }}/[0-9]*"
  become: true
...
