---
artifacts_dir: "{{ ansible_env.HOME }}/ceph-csi-artifacts"
ceph_cluster_id: ~
ceph_user_id: "kube"
ceph_user_key: ~
ceph_pool: "kube"
ceph_storageclass_name: "rbd"
template_files:
  - {dest: "{{ artifacts_dir }}/00-csi-configmap.yml"}
  - {dest: "{{ artifacts_dir }}/03-csi-rbd-secret.yml"}
  - {dest: "{{ artifacts_dir }}/08-csi-rbd-sc.yml"}
...
