---
- name: Local Repo | create burrito namespace
  kubernetes.core.k8s:
    name: burrito
    api_version: v1
    kind: Namespace
    state: present
  become: true

- name: Local Repo | clean up burrito artifacts directory
  ansible.builtin.file:
    path: "{{ artifacts_dir }}"
    state: absent

- name: Local Repo | create burrito artifacts directory
  ansible.builtin.file:
    path: "{{ artifacts_dir }}"
    state: directory

- name: Local Repo | templating template files
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ item.dest | basename }}.j2"
    mode: "0644"
  loop: "{{ template_files }}"

- name: Local Repo | apply localrepo manifests
  kubernetes.core.k8s:
    src: "{{ item }}"
    state: present
    wait: true
  with_fileglob:
    - "{{ artifacts_dir }}/[0-9]*"
  become: true

- name: Local Repo | get localrepo pod name
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ localrepo.namespace }}"
    label_selectors:
      - "k8s-app=localrepo"
  register: localrepo_pod

- name: Local Repo | debug localrepo pod information
  ansible.builtin.debug:
    msg: "{{ localrepo_pod.resources[0].metadata.name }}"

- name: Local Repo | check package src directory exists
  ansible.builtin.file:
    path: "{{ pkg_src }}"
    state: directory
  check_mode: true
  register: is_pkg_src
  
- name: Local Repo | copy packages to localrepo pod
  ansible.builtin.command: >-
    kubectl -n {{ localrepo.namespace }} cp {{ pkg_src }} \
      {{ localrepo_pod.resources[0].metadata.name }}:{{ pkg_dst }}
  become: true
  when: not is_pkg_src.changed

- name: Local Repo | take down offline services
  ansible.builtin.shell: >-
    ./offline_services.sh --down
  args:
    chdir: "{{ playbook_dir }}/scripts"
  become: true
  register: res
  failed_when: res.rc not in [0, 10]

- name: Local Repo | add repo section in haproxy.cfg
  ansible.builtin.blockinfile:
    path: "/etc/haproxy/haproxy.cfg"
    mode: "0600"
    insertafter: EOF
    marker: "# {mark} LOCAL REGISTRY/REPO BLOCK"
    block: >-
      listen localregistry
          bind :5000
          option forwardfor except 127.0.0.0/8
          balance {{ balance }}
          option httpchk GET /
          {% for h in groups['kube-master'] %}
          server {{ h }} {{ hostvars[h].ip }}:{{ registry_service_nodeport }} check inter {{ inter }} rise {{ rise }} fall {{ fall }} on-marked-down shutdown-sessions
          {% endfor %}
      listen localrepo
          bind :8001
          option forwardfor except 127.0.0.0/8
          balance {{ balance }}
          option httpchk GET /
          {% for h in groups['kube-master'] %}
          server {{ h }} {{ hostvars[h].ip }}:{{ localrepo.nodeport }} check inter {{ inter }} rise {{ rise }} fall {{ fall }} on-marked-down shutdown-sessions
          {% endfor %}
  become: true
  notify:
    - systemctl restart service
...
