---
- name: setup rados gateway user
  hosts: rgws:kube-master
  gather_facts: true
  any_errors_fatal: true

  tasks:
    - name: set auth_client_required to cephx
      ansible.builtin.command: >-
        ceph config set mon auth_client_required cephx
      become: true
      delegate_to: "{{ groups['rgws'][0] }}"
      run_once: true

  roles:
    - { role: burrito.rgw-user, tags: ['rgw-user', 'burrito']}
...
