---
- name: setup rados gateway user
  hosts: rgws:kube_control_plane
  gather_facts: true
  any_errors_fatal: true

  tasks:
    - name: set auth_client_required to cephx
      ansible.builtin.command: >-
        ceph config set mon auth_client_required cephx
      become: true
      delegate_to: "{{ groups['rgws'][0] }}"
      run_once: true
      when: '"ceph" in storage_backends'

  roles:
    - role: burrito.rgw-user
      when: '"ceph" in storage_backends'
      tags: ['rgw-user', 'burrito']
...
