---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-csi-config
  namespace: ceph-csi
data:
  config.json: |-
    [
      {
        "clusterID": "<ceph cluster id>",
        "monitors": [
          "<monitor1_ip_address>:6789",
          "<monitor2_ip_address>:6789",
          "<monitor3_ip_address>:6789"
        ]
      }
    ]
...
