---
- name: setup cert-manager
  hosts: localhost
  any_errors_fatal: true
  roles:
    - { role: burrito.cert-manager, tags: ['cert-manager', 'burrito']}

- name: setup system
  hosts: k8s_cluster
  any_errors_fatal: true
  roles:
    - { role: burrito.system, tags: ['system', 'burrito']}

- name: provision openstack
  hosts: localhost
  any_errors_fatal: true
  roles:
    - { role: burrito.openstack, tags: ['openstack', 'burrito']}
...
