---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-block-pvc
spec:
  containers:
    - name: debian
      image: debian:bullseye
      command: ["/bin/sh", "-c"]
      args: ["tail -f /dev/null"]
      volumeDevices:
        - name: data
          devicePath: /dev/xvda
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: raw-block-pvc
...
