---
- name: Genesis Registry | apply patch to csi-rbdplugin daemonset
  kubernetes.core.k8s_json_patch:
    kind: DaemonSet
    namespace: ceph-csi
    name: csi-rbdplugin
    patch: "{{ rbdplugin_patch_list }}"
  become: true
  delegate_to: localhost
  run_once: true

- name: Genesis Registry | apply patch to csi-rbdplugin-provisioner deployment
  kubernetes.core.k8s_json_patch:
    kind: Deployment
    namespace: ceph-csi
    name: csi-rbdplugin-provisioner
    patch: "{{ provisioner_patch_list }}"
  become: true
  delegate_to: localhost
  run_once: true
...
